### ISSUE TITLE
Ignore spurious whitespaces in CSS inspections 

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-html-runner#59]
For example the following css..

```css
p {
  color: rgb(255, 255, 255);
}
```

...should match `DeclaresStyle:color:rgb(255,255,255`.
