### ISSUE TITLE
Show HTML within a browser mock

### ISSUE THREAD

**Issue by flbulgarelli** [mumuki/mumuki-html-runner#6]
Add the `mu-browser` class to the iframe, and the following css: 

```css
.mu-browser {
  border-top: 2em solid rgba(230, 230, 230, 0.7);
  box-shadow: 0 0.1em 1em 0 rgba(0, 0, 0, 0.4);
  position: relative;
  border-radius: 3px 3px 0 0;
  padding: 5px;
}

.mu-browser:before {
  display: block;
  position: absolute;
  content: '';
  top: -1.25em;
  left: 0.5em;
  width: 0.5em;
  height: 0.5em;
  border-radius: 50%;
  background-color: #9b3;
  box-shadow: 0 0 0 2px #9b3;
}

   
.mu-browser:after {
  display: block;
  position: absolute;
  font-family: 'DejaVu Sans', 'Liberation Sans', sans-serif;
  content: 'http://mysite.com';
  top: -1.6em;
  left: 1.5em;
  padding: 0 0.2em;
  width: calc(100% - 2.2em);
  height: 1.2em;
  border-radius: 2px;
  background-color: white;
}

.mu-browser > * {
  display: block;
  margin: 2em;
}
```
